# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Chip8_config = debug

else ifeq ($(config),release)
  Chip8_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Chip8

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Chip8:
ifneq (,$(Chip8_config))
	@echo "==== Building Chip8 ($(Chip8_config)) ===="
	@${MAKE} --no-print-directory -C . -f Chip8.make config=$(Chip8_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f Chip8.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Chip8"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"